name: Docker Compose CI/CD with Docker Swarm

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build Docker images
      run: |
        docker build -t backend_image ./backend
        docker build -t frontend_image ./frontend
        
    - name: Initialize Docker Swarm
      run: docker swarm init 

    - name: Deploy stack
      run: docker stack deploy -c docker-compose.yaml dock

    - name: List services
      run: docker service ls


